version: '3'
services:

  web:
    build: .
    volumes:
      - './src/:/var/www/my-site/'
      - './resources/log/apache2:/var/log/apache2'
      - './resources/log/php:/var/log/php'
    ports:
      - '8080:80'
    labels:
      - traefik.docker.network=project_default
      - traefik.port=80
    depends_on:
      - mysql
    networks:
      - project_default

  mysql:
    image: 'mysql:8'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=my-site
      - MYSQL_ROOT_PASSWORD=groot
      - MYSQL_USER=groot
      - MYSQL_PASSWORD=groot
    volumes:
      - './resources/mysql:/var/lib/mysql'
    networks:
      - project_default

  traefik:
    image: 'traefik:1.6'
    command: --web --docker --docker.watch --docker.domain=local --logLevel=DEBUG
    labels:
      - traefik.docker.network=project_default
      - traefik.port=8080
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - project_default

networks:
  default:
